### ISSUE TITLE
Agenda: __

### ISSUE THREAD

**Issue by MadiMalik** [MIT-Emerging-Talent/ET6-foundations-group-30#5]
- **Date:** 25-12-2024
- **Time:** 10:00 PM PKT
- **Location:** Zoom

1. **Discuss GitHub Issues and Pull Requests**
   - Topic: How and when to use GitHub Issues and Pull Requests (Important).
   - Resource: Watch this [video](https://www.youtube.com/watch?v=TKJ4RdhyB5Y) to learn about GitHub issues.
   - Reference: [communication.md](https://github.com/MIT-Emerging-Talent/ET6-foundations-group-30/blob/main/collaboration/communication.md)

2. **Discuss and Assign the Chosen Problems**
   - Discuss and choose problems to work on.
   - Assign specific problems to each team member.

3. **Decide the Next Meeting**
   - Discuss and finalize the date and time for the next meeting.

**Comment by fatima-malik99** [comment]
At this point after this meeting I can already see that we are getting more productive and improving a lot.
